---
replicaCount: 3

image:
  repository: quay.io/cirrocloud/example-go-web-service
  tag: v1.1.2
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

hostname:
  - example.com
  - localhost

env:
  app_name: Go web service
