apiVersion: v1
kind: Service
metadata:
  name: {{ include "example-go-web-service.fullname" . }}
spec:
  type: ClusterIP
  selector:
    name: {{ include "example-go-web-service.fullname" . }}
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetport: {{ .Values.service.port }}
